### ISSUE TITLE
Release v2.0.1 doesn't contain the latest code

### ISSUE THREAD

**Issue by awasson** [veda-consulting-company/uk.co.vedaconsulting.mailchimp#358]
For some reason the release v2.0.1 isn't the latest code and still contains the permission error in CRM/Mailchimp/Permission.php on line 28. It would be helpful for those of us who are using the extension to have a more recent release so as to prevent it from taking down a website because of outdated code. 

If on the other hand is is being unsupported then I suppose a release with a notification would be useful.

Cheers,
Andrew

**Comment by mlutfy** [comment]
@veda-consulting Can you please tag a new release? (also impacts PHP 8 compatibility).

**Comment by Toby-fz** [comment]
@veda-consulting I would also love a new release!

**Comment by benrfairless** [comment]
@krishgopi @cmolava is this something that can be done 🥺

**Comment by rajeshrhino** [comment]
@awasson @mlutfy @Toby-fz New version 2.0.2 released with latest code https://github.com/veda-consulting-company/uk.co.vedaconsulting.mailchimp/releases/tag/v2.0.2

cc @krishgopi @cmolava
